### ISSUE TITLE
Issue : Controle op checkbox

### ISSUE THREAD

**Issue by TheysKlaas** [Frontend-MCT/oefening-travel-planner-TheysKlaas#1]
https://github.com/Frontend-MCT/oefening-travel-planner-TheysKlaas/blob/dc82a0b1239c3a5816f4d8bb3decda44700b2a85/src/script/app.js#L17
@MLoth 

Dag meneer, 

Ik heb een vraagje over onze opdracht.
Bij men ClearList functie kan ik de local storage terug leegmaken. 
Maar daarnaast probeer ik ook de checkboxen terug op false te zetten. 
Zou dit de juiste manier zijn? Ik vind niet echt hoe ik kan checken ofdat de state ervan effectief gewijzigd is. Bij het debuggen staat dit telkens op "undefined". 

De landen krijgen ook de opacity niet terug op 1. 

Alvast bedankt. 
Vriendelijke groeten
Klaas

**Comment by MLoth** [comment]
Wat je kan doen, is alle checkboxes overlopen en het attribuut checked verwijderen.
Als ze het niet hebben, dan geeft het niet en anders verwijder je het.
```javascript
const countries = document.querySelectorAll('.js-country');
// loop the classes and:
     country.removeAttribute('checked');
```
